language: php

php:
    - 5.5
    - 5.6
    - 7.0

install:
    - composer self-update
    - composer install

before_script:
    - php -S localhost:8081 sample-app/public/index.php &> /dev/null &

script:
    - ./vendor/bin/phpunit --config tests/phpunit/phpunit-travis.xml;
    - ./vendor/bin/phpspec run --config tests/phpspec/phpspec-travis.yml --no-interaction;
    - ./vendor/bin/behat --config tests/behat/behat.yml --suite servicelevel;
    - ./vendor/bin/behat --config tests/behat/behat.yml --suite webserver;

after_script:
    - php vendor/bin/coveralls -v
