language: php

php:
    - 5.3
    - 5.4

install:
    - composer self-update
    - composer install

before_script:
    - php -S localhost:8080 ./src-dev/src/index.php &
    - sleep 3

script:
    - vendor/bin/phpspec run --config tests/phpspec/phpspec.yml;
    - vendor/bin/phpunit --config tests/phpunit/phpunit.xml;
    - vendor/bin/behat --config tests/behat/behat.yml --suite all_features;
    - PHP_VERSION_HAS_SERVER=`php -r 'echo version_compare(PHP_VERSION, "5.4.0") >= 0;'`;
    - if [ $PHP_VERSION_HAS_SERVER ] ; then vendor/bin/behat --config tests/behat/behat.yml --suite webserver_features; ; fi ;

#after_script:
#    - php vendor/bin/coveralls -v
