language: php

php:
    - 5.5
    - 5.6

install:
    - composer self-update
    - composer install

script:
    - ./vendor/bin/phpunit --config tests/phpunit/phpunit-travis.xml;
    - ./vendor/bin/phpspec run --config tests/phpspec/phpspec-travis.yml --no-interaction;
    - ./vendor/bin/behat --config tests/behat/behat.yml;

after_script:
    - php vendor/bin/coveralls -v
