language: php

php:
    - 5.3
    - 5.4

install:
    - composer self-update
    - composer install

script:
    - vendor/bin/phpspec run --config tests/phpspec/phpspec.yml;
    - vendor/bin/phpunit --config tests/phpunit/phpunit.xml;
    - vendor/bin/behat --config tests/behat/behat.yml --suite all_features;

#after_script:
#    - php vendor/bin/coveralls -v
